### PR TITLE
Capacitor 4.0 support

### PR DESCRIPTION
**Pull request by AshleyMedway**
I think #38 is missing the podspec and gradle changes

Additional if you want to install this early in your project you can run `npm i ProteanSoftware/capacitor-filesharer#master`

### CODE REVIEW

**Comment by tho-masn** [comment]
@AshleyMedway: Did you have any troubles with this Branch, Capacitor 4 and Android so far?
I keep getting the following error:

```
E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading com.byteowls.capacitor.filesharer.FileSharerProvider uri content://com..... from pid=27862, uid=1000 requires the provider be exported, or grantUriPermission()
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:912)
        at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:830)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:708)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:247)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
        at android.os.Binder.execTransactInternal(Binder.java:1215)
        at android.os.Binder.execTransact(Binder.java:1179)
```

**Comment by moberwasserlechner** [comment]
If you are confident that this works I'm happy to merge and release a new version asap, but I do not have the time to test it myself. BR

**Comment by AshleyMedway** [comment]
Let me do some further testing today. I've got to do a regression of our app in Capacitor 4 today. Will report back :)

**Comment by tho-masn** [comment]
I've tested the branch with a few devices (iOS and Android) and everything looks good so far. The error I mentioned above is still happening on Android as soon as a file gets shared, but it doesn't seem to have any negative consequences.

**Comment by tho-masn** [comment]
@hermitdemschoenenleben Did you install the PR with `npm i ProteanSoftware/capacitor-filesharer#master` as mentioned in the first post? The description is a bit misleading and actually doesn't work. You need to install the #v4 branch in order to get the latest version, which fixes the ActivityResult.

**Comment by hermitdemschoenenleben** [comment]
@tho-masn you're right, I was indeed misled by the description and checked out the wrong branch, sorry for that! With the `v4` branch, it works fine. Thank you very much for your work and quick response!

**Comment by sander-spruit** [comment]
When will this be launched? Waiting for it.

**Comment by sander-spruit** [comment]
The import in the component now still gives 'cannot find module'

`import { FileSharer } from '@byteowls/capacitor-filesharer';`

It did install successfully

**Comment by moberwasserlechner** [comment]
I'm in the middle of releasing. Which version did you try. 4.0.0 is not released yet.

**Comment by moberwasserlechner** [comment]
@sander-spruit One more thing: I have no connection to ProteanSoftware. I have planned to do the release this weekend so your rather disrespectful behavior is for sure not the reason I'm releasing. Such comments are not motivating me to spend my spare time in providing open source software.

**Comment by sander-spruit** [comment]
@moberwasserlechner no harm intended.

**Pull request merged**
